plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: "pubver set ${nextRelease.version}"
    - publishCmd: "git add pubspec.yaml && git commit -m ${nextRelease.version} && git push"
branches:
  - master
