name: worldstate_model
description: A starting point for Dart libraries or applications.
version: 1.4.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  equatable: ^1.0.1

dev_dependencies:
  extra_pedantic: ^1.1.1+3
  test: ^1.6.1
  json_serializable: ^3.2.3
  build_runner: ^1.6.6
