name: warframestat_api_models
author: Ludwig <blacklightinglr@gmail.com>
version: 4.3.5
description: A starting point for Dart libraries or applications.
environment:
  sdk: ">=2.10.3 <3.0.0"
dependencies:
  equatable: ^1.2.5
  json_annotation: ^3.1.1
dev_dependencies:
  extra_pedantic: ^1.2.0
  test: ^1.15.5
  json_serializable: ^3.5.0
  build_runner: ^1.10.6
