name: worldstate_model
description: A starting point for Dart libraries or applications.
version: 1.2.1
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  equatable: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.1
  json_serializable: ^3.2.3
  build_runner: ^1.6.6
