name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0
      - name: Setup Dart
        uses: cedx/setup-dart@v2
      - name: Install dependacies
        run: |
          npm install -g semantic-release
          npm install -g @semantic-release/exec
          pub global activate pubspec_version
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release
